"""lang_pair

Revision ID: 0068a98df801
Revises: 0825bd9a8466
Create Date: 2025-08-26 17:34:07.754883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0068a98df801'
down_revision: Union[str, Sequence[str], None] = '0825bd9a8466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_row_words', sa.Column('lang_pair', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_row_words', 'lang_pair')
    # ### end Alembic commands ###
